### ISSUE TITLE
TypeError for update_by_query_rethrottle response validation

### ISSUE THREAD

**Issue by stevejgordon** [elastic/elastic-client-generator#86]
Running the command `./run-validations.sh --api update_by_query_rethrottle --response` tells me there are no tests but also fails with a `TypeError`.

```
Iterating over spec, found API's: 350
✔ Validated 1 endpoints (0 recordings tested, 0 skipped)
TypeError: Cannot read property 'length' of undefined
    at /home/stevejgordon/clients-flight-recorder/scripts/types-validator/index.js:146:36
    at Array.map (<anonymous>)
    at generate (/home/stevejgordon/clients-flight-recorder/scripts/types-validator/index.js:140:37)
    at Object.<anonymous> (/home/stevejgordon/clients-flight-recorder/scripts/types-validator/index.js:178:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by stevejgordon** [comment]
Seems ok now - Closing
